name: Main
on: [ push ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run main
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Main action step
        uses: ./ # Uses an action in the root directory
        id: main
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          file: ''
          dryrun: true
